export const LOGOUT = "LOGOUT";

export const GET_VERBS = "GET_VERBS";
export const SET_PRACTICE_PRETERITE = "SET_PRACTICE_PRETERITE";
export const SET_PRACTICE_PAST_PARTICIPLE = "SET_PRACTICE_PAST_PARTICIPLE";

export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";